# Use version 3 of docker compose 
version: '3'

services: 
  redis-server: 
    image: 'redis'  # Use the redis image to create the redis-server service 
  node-app: 
    restart: always 
    build: . # Look in the current directory (.) for a Dockerfile 
    ports: 
      - "4001:8081" # Our port 4001 will connect to 8081 in the container 
  # By using the same docker compose for both services, both containers will have access to each other 




